apiVersion: v1
kind: ConfigMap
metadata:
  name: faveo-env
  namespace: faveo-thetamilselvan
data:
  .env: |
  APP_URL                           = https://faveo.thetamilselvan.in
  APP_KEY                           = base64:Vkec2KWZDaAJnioIWNaOjgh7dND7kFy26pkqaAHeTso = 
  DB_TYPE                           = mysql
  DB_WRITE_HOST                     = 
  DB_READ_HOST                      = 
  DB_HOST                           = "10.43.32.188"
  DB_PORT                           = "3306"
  DB_DATABASE                       = "faveo"
  DB_USERNAME                       = "root"
  DB_PASSWORD                       = "faveo"
  DB_ENGINE                         = InnoDB
  MAIL_MAILER                       = smtp
  MAIL_HOST                         = mailtrap.io
  MAIL_PORT                         = 2525
  MAIL_USERNAME                     = null
  MAIL_PASSWORD                     = null
  CACHE_DRIVER                      = file
  SESSION_DRIVER                    = file
  SESSION_COOKIE_NAME               = faveo_9876
  QUEUE_DRIVER                      = sync
  FCM_SERVER_KEY                    = AIzaSyBJNRvyub-_-DnOAiIJfuNOYMnffO2sfw4
  FCM_SENDER_ID                     = 505298756081
  PROBE_PASS_PHRASE                 = 026a3c692c16e86a444cd7586c84cf88
  REDIS_DATABASE                    = 0
  BROADCAST_DRIVER                  = pusher
  LARAVEL_WEBSOCKETS_ENABLED        = false
  LARAVEL_WEBSOCKETS_PORT           = 6001
  LARAVEL_WEBSOCKETS_HOST           = 127.0.0.1
  LARAVEL_WEBSOCKETS_SCHEME         = http
  PUSHER_APP_ID                     = dFbafwVDgR8kSqne
  PUSHER_APP_KEY                    = 84586d746ef499f3f53b826315bf291a
  PUSHER_APP_SECRET                 = 7d17167bc90eac62013cc9a33dcaac2f
  PUSHER_APP_CLUSTER                = mt1
  MIX_PUSHER_APP_KEY                = "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER            = "${PUSHER_APP_CLUSTER}"
  SOCKET_CLIENT_SSL_ENFORCEMENT     = false
  LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT = null
  LARAVEL_WEBSOCKETS_SSL_LOCAL_PK   = null
  LARAVEL_WEBSOCKETS_SSL_PASSPHRASE = null
  DB_SSL_KEY                        = 
  DB_SSL_CERT                       = 
  DB_SSL_CA                         = 
  DB_SSL_VERIFY_PEER_CERT           = false
  SCOUT_DRIVER                      = database
  MEILISEARCH_HOST                  = 
  MEILISEARCH_KEY                   = 
  ALGOLIA_APP_ID                    = 
  ALGOLIA_SECRET                    = 
  DB_INSTALL                        = 1
  APP_ENV                           = production
  JWT_SECRET                        = G4w7pA6rLoHr5aoohZ6M8SVfC5833zLFqzivNvDYd6oc7AoYfOkpyEGlBAuhlyzB